version: '3.8'

services:
  db:
    image: postgres:16
    container_name: discuss_prod_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-discuss_prod}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: discuss_prod_web
    environment:
      - MIX_ENV=prod
      - PHX_SERVER=true
      - DATABASE_URL=ecto://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB:-discuss_prod}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PHX_HOST=${PHX_HOST:-localhost}
      - PORT=${PORT:-4000}
      - POOL_SIZE=${POOL_SIZE:-10}
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-4000}/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
