import Config

config :discuss, DiscussWeb.Endpoint,
  url: [
    host: System.get_env("PHX_HOST") || "rediscusstopic.com",
    scheme: System.get_env("URL_SCHEME") || "https",
    port: String.to_integer(System.get_env("PORT") || "443")
  ],
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: [
    "//rediscusstopic.com",
    "//www.rediscusstopic.com",
    "https://rediscusstopic.com",
    "https://www.rediscusstopic.com"
  ],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :discuss, DiscussWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Discuss.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
